#ifndef VEHICLE_DATA_H
#define VEHICLE_DATA_H

#include <stdbool.h>

/*---------------------------------------------------------
 * Vehicle Sensor Data
 *
 * This structure contains all sensor values generated by
 * the sensor module. These values are processed by the ECU
 * and displayed on the dashboard.
 *--------------------------------------------------------*/
typedef struct
{
    /* Vehicle Motion */
    int speed_kmph;
    int engine_rpm;
    int gear;

    /* Analog Sensor Values */
    float coolant_temperature;
    float fuel_level;
    float battery_voltage;

    /* Digital Status Signals */
    bool engine_running;
    bool door_open;
    bool abs_active;
    bool airbag_ok;

} VehicleData;

#endif